# GitHub Funding Configuration
# Learn more: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Supported funding platforms (uncomment to enable)

# GitHub Sponsors
# github: [mrarejimmyz]

# Open Collective
# open_collective: zkvanguard

# Patreon
# patreon: zkvanguard

# Custom URLs
# custom: ['https://zkvanguard.io/donate', 'https://buymeacoffee.com/zkvanguard']
